### ISSUE TITLE
Where do child's stay

### ISSUE THREAD

**Issue by subversivo58** [pejman-hkh/simple-jquery-implement-for-toturial-point#1]
How to walk on "childs" selector?

```javascript
// how to make this?
jQuery.fn.children = function(selector) {
    // do stuff [differ of find()]
}

// me self implementation of firstChild
jQuery.fn.firstChild = function() {
    var that = this;
    return this.eq(0).each(function() {
        that.set_selector( this.firstElementChild );
    });
}

// and lastChild
jQuery.fn.lastChild = function() {
    var that = this;
    return this.eq(0).each(function() {
        that.set_selector( this.lastElementChild );
    });
}
```

The `firstChild()` and `lastChild()` has worked but I have not been able to reach a satisfactory logic for the `children()` method ... jQuery reffer this comportament:

> Given a jQuery object that represents a set of DOM elements, the .children() method allows us to search through the children of these elements in the DOM tree and construct a new jQuery object from the matching elements. The .children() method differs from .find() in that .children() only travels a single level down the DOM tree while .find() can traverse down multiple levels to select descendant elements (grandchildren, etc.) as well. Note also that like most jQuery methods, .children() does not return text nodes; to get all children including text and comment nodes, use .contents().
>
> The .children() method optionally accepts a selector expression of the same type that we can pass to the $() function. If the selector is supplied, the elements will be filtered by testing whether they match it.
>
> **font**: https://api.jquery.com/children

Do you have any suggestions?

**Comment by pejman-hkh** [comment]
You can use find function and in before selector use > that will find just first level ...

**Comment by pejman-hkh** [comment]
```js
		jQuery.fn.children = function() {
			var childs = [];
			this.each(function() {
				for( let x of this.children ) {
					childs.push( x );
				}
			});
	
			return jQuery( childs );
		}
```

**Comment by subversivo58** [comment]
Thanks

**Comment by pejman-hkh** [comment]
Your welcome
